[URL]
PREFIX,https://account.jetbrains.com/lservice/rpc/validateKey.action
PREFIX,https://account.jetbrains.com/lservice/rpc/validateLicense.action
PREFIX,https://account.jetbrains.com/lservice/rpc/obtainAgreement.action
PREFIX,https://account.jetbrains.com/lservice/rpc/obtainLicense.action
PREFIX,https://account.jetbrains.com/lservice/rpc/fetchData.action
PREFIX,https://account.jetbrains.com.cn/lservice/rpc/validateKey.action
PREFIX,https://account.jetbrains.com.cn/lservice/rpc/validateLicense.action
PREFIX,https://account.jetbrains.com.cn/lservice/rpc/obtainAgreement.action
PREFIX,https://account.jetbrains.com.cn/lservice/rpc/obtainLicense.action
PREFIX,https://account.jetbrains.com.cn/lservice/rpc/fetchData.action